### ISSUE TITLE
Fail to make in kaldi/src: CUSPARSE_SPMM_CSR_ALG2 has not been declared in this scope

### ISSUE THREAD

**Issue by yangwanzhao** [kaldi-asr/kaldi#4303]
I fail to 'make' for kaldi/src. There is a bug in kaldi/src/cudamatrix/cublas-wrappers.h related to the last update (support for Cuda 11). I am using Cuda 10.2 and the error says CUSPARSE_SPMM_CSR_ALG2 has not been declared in this scope. 

Do I need to use Cuda 11 to build it?

**Comment by dophist** [comment]
same issue here, probably due to code change in https://github.com/kaldi-asr/kaldi/commit/c0ac791cebeba3d222caf1322c139ce3db880fb6

**Comment by danpovey** [comment]
Oops.  Change _CSR_ALG2  to _DEFAULT and it should compile. @qmmn can you please fix it with an ifdef?
I think
`#if CUDA_VERSION >= 11000)`
would mean  CUDA version >= 11.0.00 (assuming that's where that starts to be defined).

**Comment by qmmn** [comment]
@danpovey 
Yessss, fixed and PRed.

**Comment by yesmung** [comment]
Hi, 
Checking for the same error, I came across this page.
And he was able to confirm that the error was resolved with @qmmn commit as below.

https://github.com/kaldi-asr/kaldi/pull/4304/commits/24008354746a5b409f3c77e1787b15c57b49c2e6

Thanks!!!

**Comment by jimbozhang** [comment]
> @danpovey
> Yessss, fixed and PRed.

Has the PR been merged? Seem this problem still exists in the latest master branch.

**Comment by danpovey** [comment]
It looks like no-one actually did craete the PR.  You could perhaps create it based on that ocmmit?

**Comment by kkm000** [comment]
I am closing this issue for now. The discussion in  #4461 seems to suggest that you have the issue resolved.  If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me please for a faster response!
