### ISSUE TITLE
./install_mkl.sh  error: 

### ISSUE THREAD

**Issue by Santhosh642003** [kaldi-asr/kaldi#4909]
./install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
Hit:1 https://packages.cloud.google.com/apt gcsfuse-focal InRelease
Hit:2 https://packages.cloud.google.com/apt cloud-sdk InRelease                
Hit:3 https://packages.cloud.google.com/apt google-fast-socket InRelease       
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Get:6 https://apt.repos.intel.com/mkl all InRelease [4438 B]        
Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease   
Hit:8 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Err:6 https://apt.repos.intel.com/mkl all InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
Reading package lists... Done
W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
./install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

I'm running this on kaggle notebook. Please help me resolve it

**Comment by mgchristensen** [comment]
My attempt to install kaldi also failed on Fedora 39.  It appears that Intel no longer supports this version of MKL; specifically, the package signing keys are no longer valid.  I get these error messages:

`extras/install_mkl.sh: Your system is using fedora-style package management.
+ rpm --import https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
warning: Certificate 1A8497B11911E097:
  The certificate is expired: The primary key is not live
  Subkey 1A8497B11911E097 is expired: The primary key is not live
  Certificate does not have any usable signing keys
warning: Certificate ACFA9FC57E6C5DBE:
  The certificate is expired: The primary key is not live
  Subkey ACFA9FC57E6C5DBE is expired: The primary key is not live
  Certificate does not have any usable signing keys
warning: Certificate 36B9569B3F1A1BC7:
  The certificate is expired: The primary key is not live
  Subkey 36B9569B3F1A1BC7 is expired: The primary key is not live
  Certificate does not have any usable signing keys
`
Intel currently supports the newer version, renamed oneAPI MKL, available at this URL:
https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html.

Intel requires one to establish an account (no charge) in order to download and install this library.

Perhaps the developers will be able to substitute the newer libraqry for the old?

**Comment by NefelibataJay** [comment]
Resolved https://github.com/kaldi-asr/kaldi/issues/4903#issuecomment-2019813704

> ./install_mkl.sh: Your system is using debian-style package management.
> 
> * apt-get update
>   Hit:1 https://packages.cloud.google.com/apt gcsfuse-focal InRelease
>   Hit:2 https://packages.cloud.google.com/apt cloud-sdk InRelease
>   Hit:3 https://packages.cloud.google.com/apt google-fast-socket InRelease
>   Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
>   Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
>   Get:6 https://apt.repos.intel.com/mkl all InRelease [4438 B]
>   Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease
>   Hit:8 http://archive.ubuntu.com/ubuntu focal-updates InRelease
>   Hit:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease
>   Err:6 https://apt.repos.intel.com/mkl all InRelease
>   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
>   Reading package lists... Done
>   W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
>   E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
>   N: Updating from such a repository can't be done securely, and is therefore disabled by default.
>   N: See apt-secure(8) manpage for repository creation and user configuration details.
>   ./install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.
> 
> Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you believe this is a bug.
> 
> I'm running this on kaggle notebook. Please help me resolve it

**Comment by NefelibataJay** [comment]
```shell
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
apt update

extras/install_mkl.sh
```

> Resolved [#4903 (comment)](https://github.com/kaldi-asr/kaldi/issues/4903#issuecomment-2019813704)
> 
> > ./install_mkl.sh: Your system is using debian-style package management.
> > 
> > * apt-get update
> >   Hit:1 https://packages.cloud.google.com/apt gcsfuse-focal InRelease
> >   Hit:2 https://packages.cloud.google.com/apt cloud-sdk InRelease
> >   Hit:3 https://packages.cloud.google.com/apt google-fast-socket InRelease
> >   Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
> >   Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
> >   Get:6 https://apt.repos.intel.com/mkl all InRelease [4438 B]
> >   Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease
> >   Hit:8 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> >   Hit:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> >   Err:6 https://apt.repos.intel.com/mkl all InRelease
> >   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
> >   Reading package lists... Done
> >   W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
> >   E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
> >   N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> >   N: See apt-secure(8) manpage for repository creation and user configuration details.
> >   ./install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.
> > 
> > Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you believe this is a bug.
> > I'm running this on kaggle notebook. Please help me resolve it

**Comment by Errorbot1122** [comment]
@kkm000 I think the issue is back 🙁 

```
@Errorbot1122 ➜ /workspaces/actual-voice-modifier (main) $ sudo external/kaldi/tools/extras/install_mkl.sh 
external/kaldi/tools/extras/install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
Hit:1 http://deb.debian.org/debian trixie InRelease
Hit:2 http://deb.debian.org/debian trixie-updates InRelease
Hit:3 http://deb.debian.org/debian-security trixie-security InRelease
Reading package lists... Done
+ apt-get install -y wget apt-transport-https ca-certificates gnupg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.25.0-2).
apt-transport-https is already the newest version (3.0.3).
ca-certificates is already the newest version (20250419).
gnupg is already the newest version (2.4.7-21).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
+ wget -qO- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
+ apt-key --keyring /usr/share/keyrings/intel-sw-products.gpg add -
external/kaldi/tools/extras/install_mkl.sh: line 223: apt-key: command not found
external/kaldi/tools/extras/install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.
```

_(running on a GitHub codespace with a Debian Devcontainer image)_

**Comment by kkm000** [comment]
Ugh. `apt-key` is no longer used by APT. I need to look how to hack around that.

**Comment by danijel3** [comment]
@kkm000 `intel-mkl` is a part of standard debian repo now. You only need to add `non-free` to the debian sources list:

```
sed -i '0,/Components: main/ s/Components: main/Components: main non-free/' /etc/apt/sources.list.d/debian.sources
```

Now the only issue is the darn non-free dpkg has some silly interactive questions about agreeing to the license limitations etc. Luckily I found a solution that still allows it to be used within a Dockerfile:

We start from standard debian image:
```
FROM debian:stable-slim
```

This is the sed I mentioned above:
```
RUN sed -i '0,/Components: main/ s/Components: main/Components: main non-free/' /etc/apt/sources.list.d/debian.sources
```

This is the updated `apt-get` line with `debconf-set-selections` settings (I got them by running `debconf-get-selections | grep mkl` on a system with `intel-mkl` installed):
```
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y debconf-utils && \
    printf 'libmkl-dev libmkl-rt/exact-so-3-selections multiselect\nlibmkl-dev:amd64 libmkl-rt/exact-so-3-selections multiselect\nlibmkl-rt libmkl-rt/exact-so-3-selections multiselect\nlibmkl-rt:amd64 libmkl-rt/exact-so-3-selections multiselect\nlibmkl-dev libmkl-rt/use-as-default-blas-lapack boolean true\nlibmkl-dev:amd64 libmkl-rt/use-as-default-blas-lapack boolean true\nlibmkl-rt libmkl-rt/use-as-default-blas-lapack boolean true\nlibmkl-rt:amd64 libmkl-rt/use-as-default-blas-lapack boolean true\n' | debconf-set-selections && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    g++ \
    gfortran \
    make \
    automake \
    autoconf \
    bzip2 \
    unzip \
    wget \
    sox \
    libtool \
    git \
    python3 \
    zlib1g-dev \
    ca-certificates \
    patch \
    python-is-python3 \
    intel-mkl && \
    rm -rf /var/lib/apt/lists/*
```

After that, you can use the standard `./configure`,`make` steps like before. MKL is detected correctly.

**Comment by kkm000** [comment]
@danijel3 There's more than one way to package MKL, unfortunately. [Here's a test harness](/kkm000/install_mkl) that the script had to pass — 4 package managers, 6 distros, 20 variants including then-supported versions — which I used while developing it. I didn't update it in a while, so don't be surprised by CentOS 6 or Debian 7, but Intel's own layout of library files haven't changed since 2014 for sure, if ever. But generally, if we're looking at changes in the file layout of libraries, I'll have to dust that test harness well...

> part of standard debian repo now

For all supported and recently unsupported feeds? Which Debian release did you try it on? Judging by the `.sources` extension, it's 13, 14 or 15. Does MKL come with oldstable (12) and oldoldstable (13)? I don't hold too many fingers crossed for oldoldstable repo (that's 11, a.k.a. Bullseye) having been updated with MKL.

I'm sure that Debian don't install them under `/opt/intel`, `/opt` is a machine's owner directory. So, Kaldi's `./configure` picked up the Debian-packaged MKL libraries from the get-go. That's a practical option to keep in mind. Thanks for looking into this, really appreciate it!
